-- apply changes
create table users (
  id                            bigint generated by default as identity not null,
  email                         varchar(255) not null,
  constraint pk_users primary key (id)
);

