-- apply changes
create table recordings (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  recording                     bytea,
  user_id                       bigint not null,
  when_created                  timestamptz not null,
  when_modified                 timestamptz not null,
  constraint pk_recordings primary key (id)
);

create index ix_recordings_user_id on recordings (user_id);
alter table recordings add constraint fk_recordings_user_id foreign key (user_id) references users (id) on delete restrict on update restrict;

